import { test } from 'node:test';
import assert from 'node:assert/strict';
import { defaultProject, PRESETS, initialState, simulate, validate, parseDescription, qmkSource, keysForLayout } from '../lib/engine.mjs';
import { bundleFiles } from '../lib/export.mjs';
function type(p,seq){let s=initialState();for(const k of seq)s=simulate(p,s,k,100);return s;}
test('Lemon Magic and adaptive Repeat preserve recovered examples',()=>{const p=defaultProject();for(const [seq,out] of [[['i','MAGIC'],'ion'],[['m','MAGIC'],'ment'],[['SPACE','MAGIC'],' the'],[['a','REPEAT'],'and'],[['i','REPEAT'],'ing'],[['w','REPEAT'],'which']])assert.equal(type(p,seq).text,out);});
test('QMK continuation generates ions then plural repeat',()=>{const p={...defaultProject(),...PRESETS.qmk};assert.equal(type(p,['i','MAGIC','REPEAT']).text,'ions');});
test('programming fences move the insertion cursor',()=>{const p={...defaultProject(),...PRESETS.code};const s=type(p,['"','MAGIC','x']);assert.equal(s.text,'"""x"""');assert.equal(s.cursor,4);assert.equal(type(p,['.','MAGIC','REPEAT']).text,'../../');});
test('expired cases fall back to last character',()=>{const p=defaultProject();const s=simulate(p,initialState(),'i',1);assert.equal(simulate(p,s,'MAGIC',4000).text,'ii');});
test('parser accepts exact descriptions and fails whole unknown instructions',()=>{assert.deepEqual(parseDescription('after i type "on"\nspace -> the').map(r=>[r.after,r.output]),[['i','on'],[' ','the']]);assert.throws(()=>parseDescription('make me a sandwich'));});
test('validation rejects source injection, wrong hardware and duplicate cases',()=>{const p=defaultProject();assert.throws(()=>validate({...p,keys:['KC_A); evil();',...p.keys.slice(1)]}));assert.throws(()=>validate({...p,magic:[p.magic[0],p.magic[0]]}));assert.throws(()=>validate({...p,board:'unknown'}));assert.throws(()=>validate({...p,magicTimeout:0}));});
test('C strings escape quotes and backslashes safely',()=>{const p={...defaultProject(),magic:[{after:'a',output:'";evil();\\',repeat:'',cursor:0}]};assert.match(qmkSource(p),/\\";evil\(\);\\\\/);});
test('Vial has matching custom keycode order and physical unlock coordinates',()=>{const f=bundleFiles(defaultProject(),'vial');const def=JSON.parse(f['keyboards/planck/rev6/keymaps/vial/vial.json']);assert.deepEqual(def.customKeycodes.map(k=>k.name),['Magic','Repeat']);assert.deepEqual(def.matrix,{rows:8,cols:6});assert.equal(def.layouts.keymap.flat().length,48);assert.match(f['keyboards/planck/rev6/keymaps/vial/config.h'],/VIAL_UNLOCK_COMBO_ROWS \{0, 4\}/);});
test('ZMK package pins fork, includes exact Urchin hardware, rejects unsupported continuation',()=>{const p={...defaultProject(),board:'urchin',keys:keysForLayout('Magic Sturdy',34)};const f=bundleFiles(p,'zmk');assert.match(f['config/urchin.keymap'],/behavior-antecedent-morph/);assert.ok(f['config/boards/shields/urchin/urchin_left.overlay']);assert.throws(()=>bundleFiles({...p,...PRESETS.qmk},'zmk'),/cannot apply/);});
test('GitHub client rejects foreign hosts and sends project as data',async()=>{const {checkRepository,dispatchBuild}=await import('../lib/github-build.mjs');assert.throws(()=>checkRepository('https://evil.example'));assert.throws(()=>checkRepository('owner/repo/../../other'));const calls=[];const fake=async(url,options)=>{calls.push({url,options});return {ok:true,status:options.method==='POST'?204:200,json:async()=>({default_branch:'main'})};};const p=defaultProject();const result=await dispatchBuild('someone/magic-keys','test-token',p,'via',fake);assert.ok(result.requestId);assert.ok(calls.every(c=>c.url.startsWith('https://api.github.com/repos/someone/magic-keys')));assert.deepEqual(JSON.parse(JSON.parse(calls[1].options.body).inputs.project),p);});
