import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { defaultProject, PRESETS, qmkSource } from '../lib/engine.mjs';
const basic={A:4,Z:29,1:30,0:39,ENT:40,ESC:41,BSPC:42,TAB:43,SPC:44,MINS:45,EQL:46,LBRC:47,RBRC:48,BSLS:49,SCLN:51,QUOT:52,GRV:53,COMM:54,DOT:55,SLSH:56,LEFT:80,LCTL:224,RGUI:231};
const header=`#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n#include <string.h>\n#include <stdio.h>\n#include <assert.h>\n#define PROGMEM\n#define MATRIX_ROWS 1\n#define MATRIX_COLS 1\n#define LAYOUT_ortho_4x12(...) {{0}}\n#define QK_KB_0 0x7e00\n#define MOD_MASK_SHIFT 0x22\n#define IS_QK_MODS(k) ((k)>=0x100 && (k)<0x2000)\n#define QK_MODS_GET_MODS(k) ((k)>>8)\n#define QK_MODS_GET_BASIC_KEYCODE(k) ((k)&255)\n${Object.entries(basic).map(([k,v])=>`#define KC_${k} ${v}`).join('\n')}\ntypedef struct {struct {bool pressed;} event;} keyrecord_t;\nstatic uint8_t test_mods,test_weak,test_oneshot;\nstatic uint32_t clock_now;\nstatic char buffer[256]; static size_t position;\nuint8_t get_mods(void){return test_mods;} uint8_t get_weak_mods(void){return test_weak;} uint8_t get_oneshot_mods(void){return test_oneshot;}\nvoid clear_mods(void){test_mods=0;}void clear_weak_mods(void){test_weak=0;}void clear_oneshot_mods(void){test_oneshot=0;}\nvoid set_mods(uint8_t m){test_mods=m;}void set_weak_mods(uint8_t m){test_weak=m;}void set_oneshot_mods(uint8_t m){test_oneshot=m;}void send_keyboard_report(void){}\nuint32_t timer_read32(void){return clock_now;} uint32_t timer_elapsed32(uint32_t t){return clock_now-t;}\nvoid send_string(const char *s){size_t n=strlen(s),tail=strlen(buffer+position);assert(position+n+tail<sizeof(buffer));memmove(buffer+position+n,buffer+position,tail+1);memcpy(buffer+position,s,n);position+=n;}\nvoid tap_code(uint8_t k){if(k==KC_LEFT && position)position--;}\n`;
function run(p,body){mkdirSync('work',{recursive:true});const dir=mkdtempSync(resolve('work/native-'));writeFileSync(dir+'/mock.h',header);writeFileSync(dir+'/test.c',`#define QMK_KEYBOARD_H "mock.h"\n${qmkSource(p)}\nstatic void reset(void){buffer[0]=0;position=0;last_char=0;last_time=0;clock_now=0;continuation="";test_mods=test_weak=test_oneshot=0;}\nstatic void press(uint16_t code){keyrecord_t r={.event={.pressed=true}};if(process_record_user(code,&r)){char c=mk_character(code,test_mods);if(c){char s[2]={c,0};send_string(s);}}r.event.pressed=false;process_record_user(code,&r);}\nint main(void){${body}return 0;}\n`);execFileSync('cc',['-std=c11','-Wall','-Wextra','-Werror','-Wno-unused-variable','-Wno-unused-function',dir+'/test.c','-o',dir+'/test']);execFileSync(dir+'/test');}
test('compiled C produces recovered n-grams, fallback, shortcut isolation and modifier restoration',()=>{run(defaultProject(),`reset();press(KC_A+8);press(MK_MAGIC);assert(strcmp(buffer,"ion")==0);reset();press(KC_A);press(MK_REPEAT);assert(strcmp(buffer,"and")==0);reset();press(KC_A+8);clock_now=4000;press(MK_MAGIC);assert(strcmp(buffer,"ii")==0);reset();press(KC_A+8);test_mods=1;press(MK_MAGIC);assert(strcmp(buffer,"i")==0);assert(test_mods==1);reset();press(KC_A+8);test_mods=2;press(MK_MAGIC);assert(strcmp(buffer,"ion")==0);assert(test_mods==2);`);assert.ok(true);});
test('compiled C continuation and quote cursor agree with actual intended keystrokes',()=>{run({...defaultProject(),...PRESETS.qmk},`reset();press(KC_A+8);press(MK_MAGIC);press(MK_REPEAT);assert(strcmp(buffer,"ions")==0);`);run({...defaultProject(),...PRESETS.code},`reset();test_mods=2;press(KC_QUOT);test_mods=0;press(MK_MAGIC);press(KC_A+23);assert(strcmp(buffer,"\\\"\\\"\\\"x\\\"\\\"\\\"")==0);assert(position==4);`);});
