'use client';
import { useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { dispatchBuild, readBuild } from '@/lib/github-build.mjs';
import { bundleFiles } from '@/lib/export.mjs';
export default function FirmwareBuild({project,mode}:{project:any;mode:string}){
 const [open,setOpen]=useState(false);const [repo,setRepo]=useState('');const [token,setToken]=useState('');const [build,setBuild]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const latest=useRef(build);latest.current=build;
 useEffect(()=>{if(!build||build.status==='completed'||!token)return;let cancelled=false;const id=setInterval(async()=>{try{const result=await readBuild(latest.current,token);if(!cancelled){setBuild(result);setError('');}}catch(e){if(!cancelled)setError((e as Error).message);}},12000);return()=>{cancelled=true;clearInterval(id);};},[build?.requestId,build?.status,token]);
 async function start(){setBusy(true);setError('');try{bundleFiles(project,mode);setBuild(await dispatchBuild(repo,token,project,mode));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="firmware-build"><Button variant="outline" className="wide" onClick={()=>setOpen(!open)}>{open?'Hide build settings':'Build a flash file'}</Button>{open&&<div className="build-settings"><p>Build in your own GitHub fork. Your token is kept in memory and sent only to GitHub.</p><ol><li><a href="https://github.com/YesterdaysLemon/magic-keys/fork" target="_blank" rel="noreferrer">Fork Magic Keys</a> and enable Actions.</li><li>Create a fine-grained token for that fork, with Actions read/write and Contents read.</li></ol><label>Your fork<Input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="your-name/magic-keys" autoComplete="off"/></label><label>GitHub token<Input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" spellCheck={false}/></label><Button className="wide" disabled={busy||!!(build&&build.status!=='completed')} onClick={start}>{busy?'Submitting…':'Compile this project'}</Button>{token&&<Button variant="ghost" onClick={()=>setToken('')}>Forget token</Button>}{build&&<div role="status"><p>{build.status==='completed'?(build.conclusion==='success'?'Firmware compiled. Download the matching flash artifact.':`Build ${build.conclusion}. Open the log for details.`):`Build ${build.status}. You can leave this running on GitHub.`}</p><a href={build.url} target="_blank" rel="noreferrer">View build and logs ↗</a>{build.artifacts?.map((a:any)=><a className="artifact-link" key={a.id} href={a.url} target="_blank" rel="noreferrer">Download {a.name} ↗</a>)}</div>}{error&&<p role="alert" className="build-error">{error}</p>}</div>}</div>;
}
