'use client';
import { useEffect, useState } from 'react';
import { Sparkles, ArrowRight, Download, Plus, Trash2, RotateCcw, Keyboard, SlidersHorizontal, Code2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import FirmwareBuild from './firmware-build';
import { defaultProject, PRESETS, LAYOUTS, keysForLayout, parseDescription, simulate, initialState, validate, qmkSource } from '@/lib/engine.mjs';

type Rule={after:string;output:string;repeat:string;cursor:number};
export default function Home(){
 const [project,setProject]=useState(defaultProject);
 const [tab,setTab]=useState<'magic'|'repeat'>('magic'); const [view,setView]=useState('cases');
 const [description,setDescription]=useState('after i type "on"\nafter m type "ent"\nspace -> the');
 const [status,setStatus]=useState(''); const [sim,setSim]=useState(initialState);const [selected,setSelected]=useState<number|null>(null);
 const [mode,setMode]=useState('via');const [ready,setReady]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem('magic-keys-project');if(raw)setProject(validate(JSON.parse(raw)));}catch{setStatus('Your saved project could not be loaded. The default is ready.');}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('magic-keys-project',JSON.stringify(project));}catch{setStatus('Browser storage unavailable. Export your project to keep a copy.');}},[project,ready]);
 const rules:Rule[]=project[tab];
 const update=(i:number,patch:Partial<Rule>)=>setProject({...project,[tab]:rules.map((r,n)=>n===i?{...r,...patch}:r)});
 const play=(key:string)=>setSim((s:any)=>simulate(project,s,key));
 function save(name:string,data:string,type='application/json'){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function exportFirmware(){try{validate(project);const {downloadBundle}=await import('@/lib/export.mjs');await downloadBundle(project,mode);setStatus('Build project downloaded. Follow its README to compile the firmware for this exact board.');}catch(e){setStatus((e as Error).message);}}
 const changeBoard=(board:string)=>{setProject({...project,board,keys:keysForLayout(project.layout,board==='urchin'?34:48)});setMode(board==='urchin'?'zmk':'via');setSelected(null);};
 return <main>
  <header className="masthead"><a className="brand" href="/"><span className="brand-icon"><Sparkles size={21}/></span>Magic Keys<span className="edition">WORKSHOP 01</span></a><a className="source-link" href="https://github.com/YesterdaysLemon/magic-keys" target="_blank" rel="noreferrer"><Code2 size={17}/> Open source <ArrowRight size={16}/></a></header>
  <section className="intro"><div><p className="eyebrow">A LITTLE CONTEXT. A LOT FEWER KEYSTROKES.</p><h1>Your keyboard.<br/><span>Your kind of magic.</span></h1><p>Give a key a memory. Make it finish a word, fix an awkward reach, or write what comes next.</p></div><div className="example"><span className="example-label">ONE KEY. MANY POSSIBILITIES.</span><div><kbd>i</kbd><span>+</span><kbd className="magic-cap">✦</kbd><ArrowRight/><strong>ion<span className="caret"/></strong></div><small>The key remembers what came before.</small></div></section>
  <div className="workspace">
   <aside className="sidebar"><div className="section-label"><Keyboard size={16}/> YOUR KEYBOARD</div><label>Hardware<select value={project.board} onChange={e=>changeBoard(e.target.value)}><option value="planck/rev6">Planck rev6 · 48 keys</option><option value="urchin">Urchin · nice!nano v2</option></select></label><label>Base layout<select value={project.layout} onChange={e=>setProject({...project,layout:e.target.value,keys:keysForLayout(e.target.value,project.keys.length)})}>{Object.keys(LAYOUTS).map(x=><option key={x}>{x}</option>)}</select></label><div className="sidebar-divider"/><div className="section-label"><Sparkles size={16}/> START WITH A RECIPE</div>{Object.entries(PRESETS).map(([id,p]:any)=><button className="recipe" key={id} onClick={()=>{setProject({...project,...structuredClone(p),name:project.name});setSim(initialState());setStatus(`${p.name} loaded.`);}}><span>{p.name}</span><small>{p.description}</small></button>)}<p className="local-note">Your work stays in this browser.<br/>Export a project to keep or share it.</p><Button variant="outline" className="wide" onClick={()=>save('magic-keys.json',JSON.stringify(project,null,2))}>Save project</Button><label className="import-label">Open a project<input type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>100000)throw Error('Project is too large.');const p=validate(JSON.parse(await f.text()));setProject(p);setMode(p.board==='urchin'?'zmk':'via');setStatus('Project opened.');}catch(e){setStatus((e as Error).message);}}}/></label></aside>
   <section className="editor"><div className="panel-heading"><div><span className="step">01</span><h2>Make it yours</h2></div><span className="subtle">Click a key to remap it</span></div><div className={'keyboard '+(project.board==='urchin'?'split':'')}>{project.keys.map((key:string,i:number)=><button key={i} aria-label={`Key ${i+1}: ${key}`} aria-pressed={selected===i} onClick={()=>setSelected(selected===i?null:i)} className={`key ${key==='MAGIC'?'magic':key==='REPEAT'?'repeat':''} ${selected===i?'selected':''}`}><span>{key==='MAGIC'?'✦':key==='REPEAT'?'↻':key==='SPACE'?'␣':key==='BSPC'?'⌫':key==='MO(1)'?'Fn':key.length>3?key.slice(0,3):key.toUpperCase()}</span></button>)}</div>{selected!==null&&<div className="remap"><label>Key {selected+1}<Input aria-label="Key assignment" value={project.keys[selected]} onChange={e=>setProject({...project,keys:project.keys.map((k:string,i:number)=>i===selected?e.target.value:k)})}/></label><Button variant="outline" onClick={()=>setProject({...project,keys:project.keys.map((k:string,i:number)=>i===selected?'MAGIC':k)})}>✦ Magic</Button><Button variant="outline" onClick={()=>setProject({...project,keys:project.keys.map((k:string,i:number)=>i===selected?'REPEAT':k)})}>↻ Repeat</Button></div>}<div className="key-legend"><span><i/> Magic</span><span><i className="blue"/> Adaptive Repeat</span><span>US host layout</span></div>
   <div className="behavior-heading"><div className="tabs"><button className={tab==='magic'?'active':''} onClick={()=>setTab('magic')}>✦ Magic</button><button className={tab==='repeat'?'active':''} onClick={()=>setTab('repeat')}>↻ Repeat</button></div><div className="view-switch"><button aria-label="Edit cases" className={view==='cases'?'active':''} onClick={()=>setView('cases')}><SlidersHorizontal size={16}/></button><button aria-label="View QMK source" className={view==='source'?'active':''} onClick={()=>setView('source')}><Code2 size={16}/></button></div></div>
   {view==='source'?<pre className="source-code">{(()=>{try{return qmkSource(project);}catch(e){return (e as Error).message;}})()}</pre>:<><div className="describe"><label htmlFor="description">Describe your {tab==='magic'?'Magic':'Repeat'} key</label><Textarea id="description" value={description} onChange={e=>setDescription(e.target.value)} rows={3}/><div><small>Use “after i type on” or “space → the”, one case per line.</small><Button onClick={()=>{try{const parsed=parseDescription(description);validate({...project,[tab]:parsed});setProject({...project,[tab]:parsed});setStatus('Description converted. Review the cases below.');}catch(e){setStatus((e as Error).message);}}}>Create cases <ArrowRight size={16}/></Button></div></div><div className="case-heading"><h3>When this comes before…</h3><label>Within <input type="number" min="100" max="10000" value={project[`${tab}Timeout`]} onChange={e=>setProject({...project,[tab+'Timeout']:Number(e.target.value)})}/> ms</label></div><div className="table-scroll"><table><thead><tr><th>After</th><th>Type this</th><th>Then Repeat</th><th>Cursor ←</th><th/></tr></thead><tbody>{rules.map((r,i)=><tr key={i}><td><Input aria-label={`Case ${i+1} after`} value={r.after===' '?'SPACE':r.after} onChange={e=>update(i,{after:e.target.value==='SPACE'?' ':e.target.value})}/></td><td><Input aria-label={`Case ${i+1} output`} value={r.output} onChange={e=>update(i,{output:e.target.value})}/></td><td><Input aria-label={`Case ${i+1} continuation`} value={r.repeat} placeholder="repeat last" onChange={e=>update(i,{repeat:e.target.value})}/></td><td><Input type="number" aria-label={`Case ${i+1} cursor`} min={0} max={48} value={r.cursor} onChange={e=>update(i,{cursor:Number(e.target.value)})}/></td><td><Button variant="ghost" aria-label={`Remove case ${i+1}`} onClick={()=>setProject({...project,[tab]:rules.filter((_,n)=>n!==i)})}><Trash2 size={14}/></Button></td></tr>)}</tbody></table></div><Button variant="ghost" className="add-case" onClick={()=>setProject({...project,[tab]:[...rules,{after:'',output:'',repeat:'',cursor:0}]})}><Plus size={16}/> Add a case</Button><p className="hint">No matching case? Repeat the last character. Cases are exact and case-sensitive.</p></>}
   </section>
   <aside className="right-panel"><div className="panel-heading"><div><span className="step">02</span><h2>Try the feeling</h2></div><Button variant="ghost" aria-label="Reset playground" onClick={()=>setSim(initialState())}><RotateCcw size={15}/></Button></div><p className="subtle">Type below, then press a magic key.</p><div className="playground" tabIndex={0} role="textbox" aria-label="Magic key playground" onKeyDown={e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.length===1){e.preventDefault();play(e.key);}if(e.key==='Backspace'){e.preventDefault();play('BSPC');}}}>{sim.text.slice(0,sim.cursor)}<span className="caret"/>{sim.text.slice(sim.cursor)}{!sim.text&&<span className="placeholder">Try typing i…</span>}</div><div className="play-actions"><Button className="magic-action" onClick={()=>play('MAGIC')}>✦ Magic</Button><Button variant="outline" onClick={()=>play('REPEAT')}>↻ Repeat</Button></div><div className="trace"><span className="status-dot"/>{sim.message}</div><div className="sidebar-divider"/><div className="panel-heading"><div><span className="step">03</span><h2>Take it to your board</h2></div></div><label>Firmware<select value={mode} onChange={e=>setMode(e.target.value)}>{project.board==='urchin'?<option value="zmk">ZMK · antecedent-morph fork</option>:<><option value="via">QMK + VIA</option><option value="vial">Vial</option><option value="qmk">QMK</option></>}</select></label><p className="export-note">Export a complete build project for your selected hardware. Compile it to get the actual flash file.</p><Button className="wide export-button" onClick={exportFirmware}><Download size={17}/> Export build project</Button><FirmwareBuild project={project} mode={mode}/><div className="compatibility"><strong>{project.board==='urchin'?'ZMK behavior support':'VIA / Vial ready'}</strong><p>{project.board==='urchin'?'Uses your pinned antecedent-morph fork. VIA and Vial do not configure ZMK.':'Magic and Repeat are custom keycodes. Remap them after flashing; changing their rules requires a new build.'}</p></div><a className="build-link" href="https://github.com/YesterdaysLemon/magic-keys/actions/workflows/firmware.yml" target="_blank" rel="noreferrer">Compile a project on GitHub <ArrowRight size={14}/></a></aside>
  </div><div className="notice" role="status" aria-live="polite">{status}</div><footer><span>Magic Keys <span className="subtle"> / A keyboard with a little memory.</span></span><span>Inspired by Magic Sturdy · Built in the open</span></footer>
 </main>;
}
